apiVersion: v1
kind: Service
metadata:
  name: ubuntu-svc
  labels:
    app: ubuntu
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: ubuntu-port
  selector:
    app: ubuntu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:noble
        command:
          - "sleep"
          - "604800"
